name: nodeA
topic_rule: ^messagechannel
httpserver:
  shutdown_delay_time: 3s
  insecure_address:  172.26.160.148
  insecure_port: 8080
transport:
  websocket:
    read_buffer_size: 20
    start_ping: true
engine:
  type: rabbitmq
  rabbitmq:
    url: amqp://admin:admin@localhost:45672

